service: app-service

provider:
  name: aws
  runtime: ruby2.5
  profile: serverless
  region: ap-southeast-1
  stage: dev

functions:
  auth:
    handler: handler.auth
    events:
      - http: GET /auth
  oauth2callback:
    handler: handler.callback_handler
    events:
      - http: GET /oauth2callback
  createEvent:
    handler: handler.createEvent
    events:
      - http:
          path: createEvent
          method: post
          private: true

package:
  exclude:
    - '**'
  include:
    - app/**
    - vendor/**
    - '*.rb'

