service: app-service

provider:
  name: aws
  runtime: ruby2.5
  profile: serverless
  region: ap-southeast-1
  stage: dev

functions:
  createEvent:
    handler: handler.createEvent
    events:
      - http:
          path: createEvent
          method: post
          private: true

